package Chasflow;

import java.awt.Dimension;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory; 
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FajrulFalah
 */
public class Chasflow extends javax.swing.JFrame { 
      
    //method tabel pemasukan(
    private void tamkan (){ 
        int row = tbpemasukan.getRowCount();
        for (int a=0; a<row;a++){
            tbl.removeRow(0);
        }
        //tbl.addRow(new Object[]{
    //        nopemasukan.getSelectedItem(),idpemasukan.getText(), kekan.getText()
    //    });
       }
    
    //method tabel pengeluaran(
    private void tamran (){ 
        int row = tbpengeluaran.getRowCount();
        for (int b=0; b<row;b++){
            tbl2.removeRow(0);
        //tbl2.addRow(new Object[]{
          //  nopengeluaran.getSelectedItem(),idpengeluaran.getText(), keran.getText()
        //});
        }
        }
    /**
     * Creates new form Chasflow
     */
        public Chasflow() {
        initComponents();
        
        Dimension screenSize = 
         Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = this.getSize();
            if (frameSize.height > screenSize.height) {
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
                frameSize.width = screenSize.width;
            }
            this.setLocation(
                    (screenSize.width - frameSize.width) / 2, 
                    (screenSize.height - frameSize.height) / 2); 
    }
        //method pengeluaran( 
        private void jumkan(){
         int total = 0;
            for (int a =0; a< tbpemasukan.getRowCount(); a++){
            int amount = Integer.parseInt((String)tbpemasukan.getValueAt(a, 1));
            total += amount;
                }
            jumkan.setText(""+total);
        }
        //method pemasukan(
         private void jumran(){
            int total = 0;
            for (int b =0; b< tbpengeluaran.getRowCount(); b++){
            int amount = Integer.parseInt((String)tbpengeluaran.getValueAt(b, 1));
            total += amount;
                }
            jumran.setText(""+total);
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        aplikasi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        diagram = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpemasukan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpengeluaran = new javax.swing.JTable();
        jumkan = new javax.swing.JTextField();
        jumran = new javax.swing.JTextField();
        isidompet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nopemasukan = new javax.swing.JComboBox();
        idpemasukan = new javax.swing.JTextField();
        kekan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nopengeluaran = new javax.swing.JComboBox();
        idpengeluaran = new javax.swing.JTextField();
        keran = new javax.swing.JTextField();
        tamran = new javax.swing.JButton();
        tamkan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cash Flow Pribadi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INPUT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("OUTPUT");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 73, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Pemasukan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Pengeluaran");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Isi Dompet");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        aplikasi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        aplikasi.setText("About");
        aplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplikasiActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        diagram.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        diagram.setText("Tampilkan Diagram");
        diagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(200, 200, 200)
                .addComponent(diagram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(aplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(aplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addComponent(diagram))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 641, -1));

        tbpemasukan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbpemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Pemasukan", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tbpemasukan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 640, 106));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("Tabel Pengeluaran");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setText("Tabel Pemasukan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        tbpengeluaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbpengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Pengeluaran", "Keterangan"
            }
        ));
        jScrollPane2.setViewportView(tbpengeluaran);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 641, 106));

        jumkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumkanActionPerformed(evt);
            }
        });
        getContentPane().add(jumkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 110, -1));
        getContentPane().add(jumran, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 110, -1));

        isidompet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isidompetActionPerformed(evt);
            }
        });
        getContentPane().add(isidompet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Pemasukan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 97, -1, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel13.setText("No.");

        jLabel14.setText("Pemasukan");

        jLabel15.setText("Keterangan");

        nopemasukan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "input", "1", "2", "3", "4", "5" }));
        nopemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopemasukanActionPerformed(evt);
            }
        });

        idpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpemasukanActionPerformed(evt);
            }
        });

        kekan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kekanActionPerformed(evt);
            }
        });

        jLabel19.setText("No.");

        jLabel20.setText("Pengeluaran");

        jLabel21.setText("Keterangan");

        nopengeluaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "input", "1", "2", "3", "4", "5" }));

        tamran.setText("Tambahkan");
        tamran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamranActionPerformed(evt);
            }
        });

        tamkan.setText("Tambahkan");
        tamkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kekan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nopemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tamkan)
                        .addGap(48, 48, 48)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keran, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nopengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(tamran)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(nopemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(idpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(kekan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(nopengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(idpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(keran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamran)
                            .addComponent(tamkan))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 440, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Pengeluaran");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 97, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Get");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isidompetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isidompetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isidompetActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void kekanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kekanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kekanActionPerformed

    private void diagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagramActionPerformed
         // TODO add your handling code here:
      DefaultCategoryDataset piedata=new DefaultCategoryDataset();
        piedata.setValue(Integer.parseInt(jumkan.getText()),"warna", "Pemasukan");
        piedata.setValue(Integer.parseInt(jumran.getText()),"warna", "Pengeluaran");
        
        
        JFreeChart chart = ChartFactory.createLineChart("Isi Dompet",null,null,piedata);
        ChartFrame frame =new ChartFrame ("Diagram",chart);
        frame.setVisible(true);
        frame.setBounds(500, 200, 500, 500);
    }//GEN-LAST:event_diagramActionPerformed

    private void tamkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamkanActionPerformed
        // TODO add your handling code here:
        try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/cashflow","root","");
        cn.createStatement().executeUpdate("insert into tbpemasukan values"+"('"+nopemasukan.getSelectedItem()+"','"+idpemasukan.getText()+"','"+kekan.getText()+"')");
         } catch (SQLException ex) {
            Logger.getLogger(Chasflow.class.getName()).log(Level.SEVERE, null, ex);
        }
        tamkan();
        data();
        jumkan();
    }//GEN-LAST:event_tamkanActionPerformed

    private void tamranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamranActionPerformed
        // TODO add your handling code here:
        try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/cashflow","root","");
        cn.createStatement().executeUpdate("insert into tbpengeluaran values"+"('"+nopengeluaran.getSelectedItem()+"','"+idpengeluaran.getText()+"','"+keran.getText()+"')");
         } catch (SQLException ex) {
            Logger.getLogger(Chasflow.class.getName()).log(Level.SEVERE, null, ex);
        }
        tamran();
        data1();
        jumran();
    }//GEN-LAST:event_tamranActionPerformed

    private void jumkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumkanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int bil1;
        int bil2;
        int hasil1;
        bil1 = Integer.parseInt(jumkan.getText());
        bil2 = Integer.parseInt(jumran.getText());
        hasil1 = bil1 - bil2;
        isidompet.setText(Integer.toString(hasil1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        tbpemasukan.setModel(tbl);
        tbpengeluaran.setModel(tbl2);
    }//GEN-LAST:event_formComponentShown

    private void idpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpemasukanActionPerformed

    private void aplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplikasiActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Nama  : Fajrul Falah \nNIM    : 32602000114"
                 + "\nProgram Chas Flow Pribadi ini bertujuan untuk mengaudit data keuangan pribadi"
                 + "\ndengan adanya program ini developer berharap pengguna dapat memantau arus keluar masuknya data keuangan"
                 + "\n"
                 + "\n"
                 + "\nRefesensi Developer"
                 + "\n"
                 + "\nTentang CRUD"
                 + "\nhttps://www.youtube.com/watch?v=ODtmn9WfMEQ&list=PLDwt0tFP6l5JRDOqNJXdive_wBdmXFSZN"
                 + "\n"
                 + "\nTentan CRUD"
                 + "\nhttps://www.youtube.com/watch?v=inhqWTyK4Mo&list=PLDwt0tFP6l5JRDOqNJXdive_wBdmXFSZN&index=2"
                 + "\n"
                 + "\nMengkoneksikan database ke java netbeans "
                 + "\nhttps://www.youtube.com/watch?v=69crN6W-jiA",
                 "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aplikasiActionPerformed

    private void nopemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopemasukanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chasflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chasflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chasflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chasflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Chasflow().setVisible(true);
            }
        });
    }

    int baris=0;
    static Object kolom[] = {"No", "Pemasukan", "Keterangan"};
    DefaultTableModel tbl = new DefaultTableModel (kolom,baris);
    
    int garis=0;
    static Object tab[] = {"No", "Pengeluaran", "Keterangan"};
    DefaultTableModel tbl2 = new DefaultTableModel (tab,garis);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplikasi;
    private javax.swing.JButton diagram;
    private javax.swing.JTextField idpemasukan;
    private javax.swing.JTextField idpengeluaran;
    private javax.swing.JTextField isidompet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumkan;
    private javax.swing.JTextField jumran;
    private javax.swing.JTextField kekan;
    private javax.swing.JTextField keran;
    private javax.swing.JComboBox nopemasukan;
    private javax.swing.JComboBox nopengeluaran;
    private javax.swing.JButton tamkan;
    private javax.swing.JButton tamran;
    private javax.swing.JTable tbpemasukan;
    private javax.swing.JTable tbpengeluaran;
    // End of variables declaration//GEN-END:variables

    private void data() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/cashflow","root","");
        ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM tbpemasukan");
        while (rs.next()){
            String data []= {rs.getString(1),rs.getString(2),rs.getString(3)};
            tbl.addRow(data);           
        }
    }   catch (SQLException ex) {
            Logger.getLogger(Chasflow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void data1() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/cashflow","root","");
        ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM tbpengeluaran");
        while (rs.next()){
            String data1 []= {rs.getString(1),rs.getString(2),rs.getString(3)};
            tbl2.addRow(data1);           
        }
    }   catch (SQLException ex) {
            Logger.getLogger(Chasflow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
